# Generated by Django 4.0.5 on 2022-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isDependent',
            field=models.BooleanField(default=False),
        ),
    ]
