# Generated by Django 4.2 on 2023-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                default="",
                max_length=100,
            ),
        ),
    ]
