# Generated by Django 4.0.5 on 2022-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_isdependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depQuestion',
            field=models.JSONField(null=True),
        ),
    ]
