# Generated by Django 4.2 on 2023-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_survey_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="dependent_questions",
            field=models.ManyToManyField(blank=True, null=True, to="surveys.question"),
        ),
        migrations.AddField(
            model_name="question",
            name="depends_on",
            field=models.ManyToManyField(blank=True, null=True, to="surveys.question"),
        ),
    ]
