# Generated by Django 4.0.5 on 2022-07-25 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0003_question_depquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='dataCollectors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
