# Generated by Django 4.0.5 on 2022-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'CHOICE'), ('OPEN', 'OPEN'), ('MEDIA', 'MEDIA')], max_length=30),
        ),
    ]
