# Generated by Django 4.0.6 on 2022-08-03 10:05

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
        ),
    ]
